[package]
name = "macrolipid"
version = "0.1.0"
authors = ["Matthew J. P. Walker <walkerm930@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.50.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.64.0"
piston2d-opengl_graphics = "0.72.0"
